version: 0.2

phases:
  install:
    commands:
      - echo "=== INSTALL PHASE ==="

  pre_build:
    commands:
      - echo "=== PRE BUILD PHASE ==="
      - ls -la

  build:
    commands:
      - echo "=== BUILD PHASE ==="
      - echo "Deploying to S3..."

  post_build:
    commands:
      - echo "=== POST BUILD PHASE ==="
      - echo "Syncing to S3..."
      - aws s3 sync . s3://cicd-test-website-sagar --delete --exclude ".git/*" --exclude "buildspec.yml"
      - echo "Deploy complete!"

artifacts:
  files:
    - '**/*'
